### ISSUE TITLE
模型下载到本地后，运行报网络连接错误

### ISSUE THREAD

**Issue by remarkableJ** [FudanDISC/DISC-FinLLM#15]
运行demo：
import torch
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation.utils import GenerationConfig
from peft import PeftModel, PeftConfig

model_path = "自己的模型路径"
model = AutoModelForCausalLM.from_pretrained(
    model_path, torch_dtype=torch.float16, device_map="auto", trust_remote_code=True
)
model.generation_config = GenerationConfig.from_pretrained(model_path)
tokenizer = AutoTokenizer.from_pretrained(
    model_path, use_fast=False, trust_remote_code=True,
)
model = PeftModel.from_pretrained(model, lora_path
)

messages = [
    {"role": "user", "content": "请解释一下什么是银行不良资产？"},
]
response = model.chat(tokenizer, messages)
print(response)

报错：
OSError: We couldn't connect to 'https://huggingface.co' to load this file, couldn't find it in the cached files and it looks like baichuan-inc/Baichuan-13B-Chat is not the path to a directory containing a file named modeling_baichuan.py.

请问是哪里搞错了吗？模型已经下载到本地，是需要改config.json文件的模型路径吗？

**Comment by lemuria-wchen** [comment]
你这个貌似是网络问题，如果模型全部下载到了本地，那path之类的变量应该设置为本地路径。

**Comment by llm172** [comment]
> 你这个貌似是网络问题，如果模型全部下载到了本地，那path之类的变量应该设置为本地路径。

我也遇到这个问题了，路径也设置为本地了，还是会有这个问题

**Comment by ALLinLLM** [comment]
+1

**Comment by voyager0003** [comment]
@remarkableJ 我解决了这个问题，具体是这样的：
1. 先下载README中的全量参数大模型[https://huggingface.co/Go4miii/DISC-FinLLM](https://huggingface.co/Go4miii/DISC-FinLLM)到本地，下载完成后，修改这个目录下的config.json 第10行：
```json
{
    ...
    "AutoModelForCausalLM": "modeling_baichuan.BaichuanForCausalLM"
    ...
}
```
2. 再下载github上的推理代码，[https://github.com/FudanDISC/DISC-FinLLM](https://github.com/FudanDISC/DISC-FinLLM)，到本地目录下，修改`cli_demo.py`，把其中的大模型路径换成本地路径。
3. 执行时加上离线环境变量：
```python
HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python cli_demo.py
```
我的python环境：
```
# Python==3.10.13
torch==2.1.2
transformers==4.30.2  # 模型仓库config.json 是 4.31.0
transformers_stream_generator==0.0.4
accelerate==0.26.1
bitsandbytes==0.43.0
sentencepiece==0.1.99
```
您可以检查accelerate和bitsandbytes是否安装成功
```python
from transformers.utils.import_utils import is_accelerate_available, is_bitsandbytes_available
assert is_accelerate_available()
assert is_bitsandbytes_available()
```
我的硬件环境：
CPU: Intel Core i7-13700K
GPU: Nvidia RTX 4090 24GB
内存：64GB

**Comment by remarkableJ** [comment]
> @remarkableJ 我解决了这个问题，具体是这样的：
> 
> 1. 先下载README中的全量参数大模型https://huggingface.co/Go4miii/DISC-FinLLM到本地，下载完成后，修改这个目录下的config.json 第10行：
> 
> ```json
> {
>     ...
>     "AutoModelForCausalLM": "modeling_baichuan.BaichuanForCausalLM"
>     ...
> }
> ```
> 
> 2. 再下载github上的推理代码，https://github.com/FudanDISC/DISC-FinLLM，到本地目录下，修改`cli_demo.py`，把其中的大模型路径换成本地路径。
> 3. 执行时加上离线环境变量：
> 
> ```python
> HF_DATASETS_OFFLINE=1 TRANSFORMERS_OFFLINE=1 python cli_demo.py
> ```
> 
> 我的python环境：
> 
> ```
> # Python==3.10.13
> torch==2.1.2
> transformers==4.30.2  # 模型仓库config.json 是 4.31.0
> transformers_stream_generator==0.0.4
> accelerate==0.26.1
> bitsandbytes==0.43.0
> sentencepiece==0.1.99
> ```
> 
> 您可以检查accelerate和bitsandbytes是否安装成功
> 
> ```python
> from transformers.utils.import_utils import is_accelerate_available, is_bitsandbytes_available
> assert is_accelerate_available()
> assert is_bitsandbytes_available()
> ```
> 
> 我的硬件环境： CPU: Intel Core i7-13700K GPU: Nvidia RTX 4090 24GB 内存：64GB

修改config可行，感谢
