### ISSUE TITLE
部署时的问题

### ISSUE THREAD

**Issue by YixinGuo0921** [FudanDISC/DISC-FinLLM#2]
![image](https://github.com/FudanDISC/DISC-FinLLM/assets/122243785/7c752230-fabb-4624-8f73-40299a0f1b13)
我直接尝试从huggingface上拉取报了如上错误

**Comment by YixinGuo0921** [comment]
用huggingface上的代码报错：AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by lemuria-wchen** [comment]
可能是 Transformers 版本问题

参考下：https://blog.csdn.net/vah101/article/details/133897592

**Comment by YixinGuo0921** [comment]
换到了4.30.2的transformers成功了，谢谢谢谢
