### ISSUE TITLE
请问怎么实现切换lora的？

### ISSUE THREAD

**Issue by sunshineyg2018** [FudanDISC/DISC-FinLLM#6]

**Comment by Go4miii** [comment]
利用peft库中load_adapter函数，就可以加载多个lora，然后需要加载时再用set_adapter函数就可以了。

**Comment by lemuria-wchen** [comment]
> 利用peft库中load_adapter函数，就可以加载多个lora，然后需要加载时再用set_adapter函数就可以了。

这部分代码，是不是也可以考虑开源一下。

**Comment by sunshineyg2018** [comment]
> > 利用peft库中load_adapter函数，就可以加载多个lora，然后需要加载时再用set_adapter函数就可以了。
> 
> 这部分代码，是不是也可以考虑开源一下。
已经很详细了 。。用set_adapter就可以了
